title = "Kushal Jayswal"
baseURL = "https://kutec.github.io"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to your content language. Supported values: en, de, es, fr, ru
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "kushaljayswal"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Kushal Jayswal"
  description = "Frontend developer and UI expert from India."
  keywords = "kushal jayswal, k jayswal, frontend developer, ui developer, india, angular, html5, css3, jquery, javascript, angularjs, bootstrap, grunt, gulp"

  # How many articles should be displayed at once?
  paginate = 5

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "E3CQNYBHOF"
  algolia_apiKey    = "f342c88a83002a4c8edc079d5cfeb1de"
  algolia_indexName = "dev_kjayz"

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Frontend Developer and UI Expert"

    # if you want to use gravatar for the header image
    gravatarEMail = "ku@kutec.co.in"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "https://en.gravatar.com/userimage/11516795/234b5038fc3af6813d55351eeafa78ac.jpg?size=90"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

  # social media profile urls for the footer links
  facebook   = "https://facebook.com/kushjays"
  twitter    = "https://twitter.com/kutec"
  googleplus = ""
  pinterest  = ""
  instagram  = ""
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/kutec"

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
